version: '3'
services:
  web:
    container_name: sasaQ.nginx
    image: nginx:1.18.0
    ports: #ポートフォワーディングの指定 ホスト側のポート：コンテナ側のポートの形式で記載　ホスト側からlocalhost8000にアクセスするとコンテナ側のlocalhostにアクセスできる
      - "8000:80"
    volumes: #ホスト・コンテナ間でのファイル共有の指定　ホスト側のパス：コンテナ側のパスの形式で記載
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app

  app:
    container_name: sasaQ.app
    build: ./docker/app
    volumes:
      - .:/var/www/html
    depends_on: #サービス同士の依存関係
      - mysql

  mysql:
    container_name: sasaQ.mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sasaQ # データベース名
      MYSQL_USER: user # ユーザー名
      MYSQL_PASSWORD: root # パスワード
      MYSQL_ROOT_PASSWORD: root # パスワード
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
